version: '3.5'

networks:
  net:


services:
  db:
    image: postgres
    container_name: db_123
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U root -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net

  back:
    container_name: backend_123
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net
